### ISSUE TITLE
The video could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by bocharsky-bw** [knpuniversity/symfony3-upgrade#3]
@Leannapelham Video in `fix-my-deprecations` chapter don't load on site https://knpuniversity.com/screencast/symfony3-upgrade/fix-my-deprecations .

Looks like a video key is right. Should we re-upload this video?

**Comment by weaverryan** [comment]
@Leannapelham ping! I also can't play this video still!
